const items = [
    { country: 'Países Bajos', capital: 'Ámsterdam' },
    { country: 'Andorra', capital: 'Andorra la Vieja' },
    { country: 'Grecia', capital: 'Atenas' },
    { country: 'Serbia', capital: 'Belgrado' },
    { country: 'Alemania', capital: 'Berlín' },
    { country: 'Suiza', capital: 'Berna' },
    { country: 'Eslovaquia', capital: 'Bratislava' },
    { country: 'Bélgica', capital: 'Bruselas' },
    { country: 'Rumanía', capital: 'Bucarest' },
    { country: 'Hungría', capital: 'Budapest' },
    { country: 'Moldavia', capital: 'Chisináu' },
    { country: 'Ciudad del Vaticano', capital: 'Ciudad del Vaticano' },
    { country: 'Dinamarca', capital: 'Copenhague' },
    { country: 'Isla de Man', capital: 'Douglas' },
    { country: 'Irlanda', capital: 'Dublín' },
    { country: 'Suecia', capital: 'Estocolmo' },
    { country: 'Reino Unido (Gibraltar)', capital: 'Gibraltar' },
    { country: 'Finlandia', capital: 'Helsinki' },
    { country: 'Ucrania', capital: 'Kiev' },
    { country: 'Malta', capital: 'La Valeta' },
    { country: 'Portugal', capital: 'Lisboa' },
    { country: 'Eslovenia', capital: 'Liubliana' },
    { country: 'Reino Unido', capital: 'Londres' },
    { country: 'Noruega (Svalbard)', capital: 'Longyearbyen' },
    { country: 'Luxemburgo', capital: 'Luxemburgo' },
    { country: 'España', capital: 'Madrid' },
    { country: 'Islas Åland', capital: 'Mariehamn' },
    { country: 'Bielorrusia', capital: 'Minsk' },
    { country: 'Mónaco', capital: 'Mónaco-Ville' },
    { country: 'Rusia', capital: 'Moscú' },
    { country: 'Chipre', capital: 'Nicosia' },
    { country: 'Noruega', capital: 'Oslo' },
    { country: 'Francia', capital: 'París' },
    { country: 'Montenegro', capital: 'Podgorica' },
    { country: 'Chequia', capital: 'Praga' },
    { country: 'Kosovo', capital: 'Pristina' },
    { country: 'Islandia', capital: 'Reikiavik' },
    { country: 'Letonia', capital: 'Riga' },
    { country: 'Italia', capital: 'Roma' },
    { country: 'Jersey', capital: 'Saint Helier' },
    { country: 'Guernsey', capital: 'Saint Peter Port' },
    { country: 'San Marino', capital: 'San Marino' },
    { country: 'Bosnia y Herzegovina', capital: 'Sarajevo' },
    { country: 'Macedonia del Norte', capital: 'Skopie' },
    { country: 'Bulgaria', capital: 'Sofía' },
    { country: 'Estonia', capital: 'Tallin' },
    { country: 'Albania', capital: 'Tirana' },
    { country: 'Islas Feroe', capital: 'Tórshavn' },
    { country: 'Liechtenstein', capital: 'Vaduz' },
    { country: 'Polonia', capital: 'Varsovia' },
    { country: 'Austria', capital: 'Viena' },
    { country: 'Lituania', capital: 'Vilna' },
    { country: 'Croacia', capital: 'Zagreb' },
];